export { default as TitleCard } from './TitleCard';
export { default as Clock } from './Clock';
export { default as Home } from './Home';
export { default as Tiles } from './Tiles';
export { default as AllTiles } from './AllTiles';
export { default as PageLinks } from './PageLinks';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as TileDetails } from './TileDetails';